defaults: &defaults
  docker:
    - image: library/node:9.11.1

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          name: Yarn
          command: yarn
      - run:
          name: Test
          command: yarn test --coverage
      - store_test_results:
          path: reports
      - store_artifacts:
          path: coverage/jest/lcov-report
          destination: reports
      - save_cache:
          paths:
            - node_modules
          key: v1-{{ checksum "yarn.lock" }}
      - run:
          name: Send code coverage
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: propeller